require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cambios", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Cambio. As you add validations to Cambio, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Cambio.create! valid_attributes
      get cambios_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cambio = Cambio.create! valid_attributes
      get cambio_url(cambio)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cambio_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      cambio = Cambio.create! valid_attributes
      get edit_cambio_url(cambio)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Cambio" do
        expect {
          post cambios_url, params: { cambio: valid_attributes }
        }.to change(Cambio, :count).by(1)
      end

      it "redirects to the created cambio" do
        post cambios_url, params: { cambio: valid_attributes }
        expect(response).to redirect_to(cambio_url(Cambio.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Cambio" do
        expect {
          post cambios_url, params: { cambio: invalid_attributes }
        }.to change(Cambio, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post cambios_url, params: { cambio: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cambio" do
        cambio = Cambio.create! valid_attributes
        patch cambio_url(cambio), params: { cambio: new_attributes }
        cambio.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cambio" do
        cambio = Cambio.create! valid_attributes
        patch cambio_url(cambio), params: { cambio: new_attributes }
        cambio.reload
        expect(response).to redirect_to(cambio_url(cambio))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        cambio = Cambio.create! valid_attributes
        patch cambio_url(cambio), params: { cambio: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cambio" do
      cambio = Cambio.create! valid_attributes
      expect {
        delete cambio_url(cambio)
      }.to change(Cambio, :count).by(-1)
    end

    it "redirects to the cambios list" do
      cambio = Cambio.create! valid_attributes
      delete cambio_url(cambio)
      expect(response).to redirect_to(cambios_url)
    end
  end
end
